config/routes.rb
Rails.application.routes.draw do
  get 'product/show'

  get 'users/new'

  root 'search#index'
  get 'search/index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :comments, only: [:create, :destroy]
  resources :products, only: [:show]

end

app/views/layouts/_footer.html.erb
<div class="footer<%= "2" if !@absoulte.nil? %>">
  <p>差评网 | <a href="#">关于我们</a> | <a href="#">联系我们</a></p>
  <p>Copyright © 占座小分队-曾旭东&汪鑫&王友军</p>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">差评网</a>
      </div>
      <nav>
        <ul class="nav navbar-nav pull-right ">
          <li><%= link_to "首页", root_path %></li>
          <% if signed_in? %>
              <li><%= link_to "用户列表", users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  账户 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "个人资料", current_user %></li>
                  <li><%= link_to "设置 ", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "注销", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "登录", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag "logo-icon.ico" %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body class="<%= "home" if !@is_home.nil? %>" role="document">
<%= render 'layouts/header' %>
<div class="container-fluid">
  <%= %>
  <% flash.each do |key, value| %>
      <div class="alert alert-danger alert-<%= key %>" role="alert"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>